name: Green River Cyclery and the Busted Bike Cafe
favicon: null
layout_spectrum: 0.87897
typography_spectrum: 0.23379
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b373d'
    - '#e0dee0'
    - '#848184'
    - '#a9a7a9'
  brandStrength: 0.75
  lightness: 0.49308098992332816
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
