name: Green River Cyclery and the Busted Bike Cafe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b373d'
    - '#e0dee0'
    - '#848184'
    - '#a9a7a9'
  brandStrength: 0
  lightness: 0.49308098992332816
  saturation: 0.8571664264891297
  rhythmicContrast: 0.7597704052459449
purpose: []
